<a href="https://colab.research.google.com/github/ruchithareddy296/2216139_AIML_BootCamp/blob/main/assignment9(sms_spam_collection).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#importing the libraries
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/content/drive/MyDrive/SMSSpamCollection',sep='\t',header=None,names=['label','message'])

In [4]:
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.shape

(5572, 2)

In [6]:
#data preprocessing
#method1-label encoder done in malaria dataset
#mehod2
df['label']=df.label.map({'ham':0,'spam':1})

In [7]:
df.head()

label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [8]:
#bag of words(BOW)

In [9]:
#DEFINE THE DOCUMENTS
doc = ['Hello,how are you!','Win money,win from home.','Call me now.','Hello,Call hello you tommorrow?']

from sklearn.feature_extraction.text import CountVectorizer
count_vector=CountVectorizer()
print(count_vector)

CountVectorizer()


In [10]:
count_vector.fit(doc)

CountVectorizer()

In [11]:
n=count_vector.get_feature_names()
print(n)

['are', 'call', 'from', 'hello', 'home', 'how', 'me', 'money', 'now', 'tommorrow', 'win', 'you']


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [12]:
doc_array=count_vector.transform(doc).toarray()

In [13]:
doc_array

array([[1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 2, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 1]])

In [14]:
#converting this array into a dataframe
freq_table= pd.DataFrame(data=doc_array,columns=n)

In [15]:
#define the documents
doc = ['Hello,how are you!','Win money,win from home.','Call me now.','Hello,Call hello you tommorrow?']

In [16]:
freq_table

are  call  from  hello  home  how  me  money  now  tommorrow  win  you
0    1     0     0      1     0    1   0      0    0          0    0    1
1    0     0     1      0     1    0   0      1    0          0    2    0
2    0     1     0      0     0    0   1      0    1          0    0    0
3    0     1     0      2     0    0   0      0    0          1    0    1

In [17]:
#load the data
#method 1
X = df.iloc[:,-1:].values #independent -- message
Y = df.iloc[:,:-1].values #dependent -- label
#method 2
#import numpy as np
#X1=np.array(df[['message']])
#Y1=np.array(df[['label']])

In [18]:
X

array([['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'],
       ['Ok lar... Joking wif u oni...'],
       ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"],
       ...,
       ['Pity, * was in mood for that. So...any other suggestions?'],
       ["The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"],
       ['Rofl. Its true to its name']], dtype=object)

In [19]:
Y

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [20]:
#split the data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=1,shuffle=True)

In [21]:
x_train

array([["Hi , where are you? We're at  and they're not keen to go out i kind of am but feel i shouldn't so can we go out tomo, don't mind do you?"],
       ['If you r @ home then come down within 5 min'],
       ["When're you guys getting back? G said you were thinking about not staying for mcr"],
       ...,
       ['CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C YA 2MORO! WHO NEEDS BLOKES'],
       ['Text & meet someone sexy today. U can find a date or even flirt its up to U. Join 4 just 10p. REPLY with NAME & AGE eg Sam 25. 18 -msg recd@thirtyeight pence'],
       ['K k:) sms chat with me.']], dtype=object)

In [22]:
y_train

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [23]:
x_test

array([['Yep, by the pretty sculpture'],
       ['Yes, princess. Are you going to make me moan?'],
       ['Welp apparently he retired'],
       ...,
       ["For real when u getting on yo? I only need 2 more tickets and one more jacket and I'm done. I already used all my multis."],
       ['I attended but nothing is there.'],
       ['Yeah do! Don‘t stand to close tho- you‘ll catch something!']],
      dtype=object)

In [24]:
y_test

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [25]:
x_train.shape

(4457, 1)

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector=CountVectorizer()

#transform the training data into freq vectors and return the matrix

training_data = count_vector.fit_transform(x_train.flatten())

#transform the testing data into freq vectors and return the matrix

testing_data = count_vector.transform(x_test.flatten())

In [27]:
training_data

<4457x7714 sparse matrix of type '<class 'numpy.int64'>'
	with 59028 stored elements in Compressed Sparse Row format>

In [28]:
testing_data

<1115x7714 sparse matrix of type '<class 'numpy.int64'>'
	with 14094 stored elements in Compressed Sparse Row format>

In [29]:
from sklearn.naive_bayes import MultinomialNB
model= MultinomialNB()
model.fit(training_data,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB()

In [30]:
y_pred=model.predict(testing_data)
np.set_printoptions(precision=2) 
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [31]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [32]:
print("Predicted value for training data:",model.score(training_data,y_train)*100)
print("Predicted value for testing data:",model.score(testing_data,y_test)*100)

Predicted value for training data: 99.23715503702041
Predicted value for testing data: 99.01345291479821


In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(y_test, y_pred) #TN FP FN TP
print("confusion matrix for traning data")
cm1=confusion_matrix(y_train,model.predict(training_data))
print(cm1)

confusion matrix for testing data
[[965   3]
 [  8 139]]
confusion matrix for traning data
[[3843   14]
 [  20  580]]


In [35]:
#randomforest
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier()
model2.fit(training_data,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier()

In [37]:
y_pred=model2.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [39]:
print("Predicted value for training data:",model2.score(training_data,y_train)*100)
print("Predicted value for testing data:",model2.score(testing_data,y_test)*100)

Predicted value for training data: 100.0
Predicted value for testing data: 98.20627802690582


In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(y_train,model2.predict(training_data))
print(cm1)

confusion matrix for testing data
[[968   0]
 [ 20 127]]
confusion matrix for traning data
[[3857    0]
 [   0  600]]


In [42]:
#decisiontree
from sklearn.tree import DecisionTreeClassifier
model3=DecisionTreeClassifier()

In [44]:
model3.fit(training_data,y_train)

DecisionTreeClassifier()

In [46]:
print("Predicted value for training data:",model3.score(training_data,y_train)*100)
print("Predicted value for testing data:",model3.score(testing_data,y_test)*100)

Predicted value for training data: 100.0
Predicted value for testing data: 97.30941704035875


In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(y_train,model3.predict(training_data))
print(cm1)

confusion matrix for testing data
[[968   0]
 [ 20 127]]
confusion matrix for traning data
[[3857    0]
 [   0  600]]


In [49]:
#logisticregression
from sklearn.linear_model import LogisticRegression
model4=LogisticRegression()

In [51]:
model4.fit(training_data,y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [53]:
print("Predicted value for training data:",model4.score(training_data,y_train)*100)
print("Predicted value for testing data:",model4.score(testing_data,y_test)*100)

Predicted value for training data: 99.75319721785955
Predicted value for testing data: 98.9237668161435


In [56]:
y_pred=model4.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [57]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(y_train,model4.predict(training_data))
print(cm1)

confusion matrix for testing data
[[967   1]
 [ 11 136]]
confusion matrix for traning data
[[3857    0]
 [  11  589]]


In [58]:
#knn
from sklearn.neighbors import KNeighborsClassifier
model5=KNeighborsClassifier()

In [59]:
model5.fit(training_data,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [61]:
print("Predicted value for training data:",model5.score(training_data,y_train)*100)
print("Predicted value for testing data:",model5.score(testing_data,y_test)*100)

Predicted value for training data: 93.56069104778999
Predicted value for testing data: 92.37668161434978


In [62]:
y_pred=model5.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [63]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(y_train,model5.predict(training_data))
print(cm1)

confusion matrix for testing data
[[968   0]
 [ 85  62]]
confusion matrix for traning data
[[3857    0]
 [ 287  313]]


In [64]:
#svc
from sklearn.svm import SVC
model6=SVC()
model6.fit(training_data,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [65]:
print("Predicted value for training data:",model6.score(training_data,y_train)*100)
print("Predicted value for testing data:",model6.score(testing_data,y_test)*100)

Predicted value for training data: 99.50639443571909
Predicted value for testing data: 98.7443946188341


In [66]:
y_pred=model6.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(y_test, y_pred) #TN FN FP TP
print("confusion matrix for traning data")
cm1=confusion_matrix(y_train,model6.predict(training_data))
print(cm1)

confusion matrix for testing data
[[967   1]
 [ 13 134]]
confusion matrix for traning data
[[3857    0]
 [  22  578]]
